const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const QUESTIONS=[...Array.from({length:5},(_,i)=>({uid:'a'+i,module:'algebra',topic:i<3?'fsu':'powers'})),...Array.from({length:5},(_,i)=>({uid:'g'+i,module:'geometry',topic:'circle',response:{kind:'number'}})),{uid:'p0',module:'numbers',topic:'proof',response:{kind:'proof'}},{uid:'p1',module:'numbers',topic:'proof',response:{kind:'solution'}},{uid:'v0',module:'vectors',topic:'dot'}];
const MODULES={algebra:{title:'Алгебра',topics:{fsu:'ФСУ',powers:'Степени'}},geometry:{title:'Геометрия',topics:{circle:'Окружность'}},numbers:{title:'Числа',topics:{proof:'Доказательства'}},vectors:{title:'Векторы',topics:{dot:'Скалярное произведение'}}};
const context={QUESTIONS,MODULES,answerFormat:q=>q.response?.kind||'choice',moduleLabel:m=>MODULES[m].title,visibleTopicEntries:m=>Object.entries(MODULES[m].topics)};
vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function isSelfReviewedTask('),source.indexOf('function statisticsEvidenceHtml(')),context);
const {studentStatistics:stats,statisticsGroup:group,evidenceStatus:status}=context;
const progress={weak:Object.fromEntries([...QUESTIONS.slice(0,5).map(q=>[q.uid,{correct:0,wrong:1}]),...QUESTIONS.slice(5,10).map(q=>[q.uid,{correct:1,wrong:0}]),['p0',{correct:3,wrong:1,selfReviewed:4}],['p1',{correct:2,wrong:1,selfReviewed:3}],['obsolete',{correct:9999,wrong:9999}]])};
let report=stats(progress),s=report.overall;
assert.equal(s.total,13);assert.equal(s.answered,12);assert.equal(s.autoSeen,10);assert.equal(s.autoSolved,5);assert.equal(s.autoCorrect,5);assert.equal(s.autoWrong,5);assert.equal(s.autoAccuracy,50);assert.equal(s.selfSeen,2);assert.equal(s.selfAttempts,7);assert.equal(s.selfCorrect,5);assert.equal(s.selfWrong,2);assert.equal(s.attempts,17);
assert.equal(report.recommendations[0].module,'algebra');assert.equal(report.recommendations[0].topic,'fsu');assert.equal(report.recommendations[0].status,'weak');assert.equal(report.strengths[0].module,'geometry');assert.equal(report.strengths[0].status,'strong');
assert(!report.recommendations.some(x=>x.module==='numbers'));assert(!report.strengths.some(x=>x.module==='numbers'));
assert.equal(status(report.modules.find(x=>x.module==='vectors')),'empty');
assert.equal(new Set(report.recommendations.map(x=>x.module)).size,report.recommendations.length);
report=stats({weak:{p0:{correct:100,wrong:0},p1:{correct:100,wrong:0}}});assert.equal(report.overall.autoAccuracy,null);assert.equal(report.strengths.length,0);assert.equal(report.recommendations.length,0);
report=stats({weak:{a0:{correct:1000,wrong:0}}});assert.equal(status(report.modules[0]),'early');assert.equal(report.strengths.length,0);
const repeated={weak:{a0:{correct:1000,wrong:0},a1:{correct:0,wrong:1},a2:{correct:0,wrong:1},a3:{correct:0,wrong:1},a4:{correct:0,wrong:1}}};
report=stats(repeated);assert.equal(report.modules[0].autoAccuracy,100);assert.equal(report.modules[0].balancedAccuracy,20);assert.equal(status(report.modules[0]),'weak');
assert.equal(status({autoSeen:5,balancedRate:.6}),'weak');assert.equal(status({autoSeen:5,balancedRate:.8}),'strong');assert.equal(status({autoSeen:5,balancedRate:.7}),'developing');assert.equal(status({autoSeen:4,balancedRate:0}),'early');
assert.equal(status({autoSeen:2,balancedRate:0},3),'early');assert.equal(status({autoSeen:3,balancedRate:0},3),'weak');
s=group(QUESTIONS,{weak:{a0:{correct:-2,wrong:Infinity},g0:{correct:'2',wrong:'1'},p0:{correct:0,wrong:1}}});assert.equal(s.autoCorrect,2);assert.equal(s.autoWrong,1);assert.equal(s.selfWrong,1);assert.equal(s.answered,2);
report=stats({weak:{a0:{wrong:1}}});assert.equal(report.recommendations[0].status,'early');assert.equal(report.strengths.length,0);
s=stats({weak:{}}).overall;assert.equal(s.answered,0);assert.equal(s.autoAccuracy,null);assert.equal(s.balancedRate,null);
console.log('PASS: unique tasks vs attempts, exact aggregate totals, self-review isolation, sample thresholds, strong/weak recommendations, obsolete IDs, invalid counters and repeated-card bias.');
